name: Setup CloudLab API

on:
  workflow_call:
    outputs:
      base_url:
        description: Base URL of the local CloudLab API
        value: ${{ jobs.setup.outputs.base_url }}
      port:
        description: Port the API is listening on
        value: ${{ jobs.setup.outputs.port }}

jobs:
  setup:    
    runs-on: ubuntu-latest
    outputs:
      base_url: ${{ steps.expose.outputs.base_url }}
      port: ${{ steps.expose.outputs.port }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone CloudLab API repository
        run: git clone https://github.com/CampusConnectWCU/terraform-provider-cloudlab-api.git

      - name: Start CloudLab API service
        run: docker-compose -f terraform-provider-cloudlab-api/docker-compose.yml up -d

      - name: Wait for CloudLab API to be ready
        run: |
            echo "Waiting for CloudLab API to be ready..."
            until curl -s -o /dev/null -w '%{http_code}' http://localhost:8080/experiment | grep -qE '^(200|400|404)$'; do
                echo "CloudLab API not ready yet, waiting..."
                sleep 5
            done
            echo "CloudLab API is ready!"

      - name: Expose outputs
        id: expose
        run: |
          echo "base_url=http://localhost:8080" >> "$GITHUB_OUTPUT"
          echo "port=8080" >> "$GITHUB_OUTPUT"